<?php
require_once '../controllers/constants.php';
require_once '../controllers/database.php';
session_start();



// Establish a database connection
$conn = connectToDatabase();


// Retrieve the form data
$name = $_POST['name'] ?? '';
$surname = $_POST['surname'] ?? '';
$email = $_POST['email'] ?? '';
$phone_number = $_POST['phone_number'] ?? '';
$password = $_POST['password'] ?? '';
$confirm_password = $_POST['confirm_password'] ?? '';
$country = $_POST['country'] ?? '';
$city = $_POST['city'] ?? '';
$street = $_POST['street'] ?? '';
$apartment = $_POST['apartment'] ?? '';
$postal_code = $_POST['postal_code'] ?? '';
$license_number = $_POST['license_number'] ?? '';

// Validate input
if (empty($name) || empty($surname) || empty($email) || empty($phone_number) || empty($password) || empty($confirm_password) || empty($country) || empty($city) || empty($street) || empty($apartment) || empty($postal_code) || empty($license_number)) {
    die("<h1>All fields are required!</h1>");
}

// Check if the passwords match
if ($password !== $confirm_password) {
    die("<h1>Passwords do not match!</h1>");
}

// Check if the email already exists
$stmt = $conn->prepare("SELECT user_id FROM users WHERE email = ?");
$stmt->bind_param("s", $email);
$stmt->execute();
$stmt->store_result();

if ($stmt->num_rows > 0) {
    echo "<h1>Email is already registered!</h1>";
    $stmt->close();
    $conn->close();
    exit;
}
$stmt->close();

// Hash the password
$hashed_password = password_hash($password, PASSWORD_DEFAULT);

// Insert the new user into the database
$stmt = $conn->prepare("INSERT INTO users (name, surname, email, phone_number, password, country, city, street, apartment, postal_code, license_number) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
$stmt->bind_param("sssssssssss", $name, $surname, $email, $phone_number, $hashed_password, $country, $city, $street, $apartment, $postal_code, $license_number);

if ($stmt->execute()) {
    $_SESSION['user_id'] = $stmt->insert_id;  // The user_id generated by the INSERT statement
    $_SESSION['user_name'] = $name;
    $_SESSION['user_email'] = $email;

    // Redirect to the user profile page
    header("Location: " . BASE_REDIRECT_URL . 'profile');
    exit;
} else {
    echo "<h1>Registration failed. Please try again.</h1>";
}

$stmt->close();
closeConnection($conn);
